//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoutingAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCOUTING2019
    {
        public int Id { get; set; }
        public int NUM { get; set; }
        public string NAME { get; set; }
        public Nullable<int> RANK { get; set; }
        public Nullable<byte> RCKT_HATCH_H { get; set; }
        public Nullable<byte> RCKT_HATCH_M { get; set; }
        public Nullable<byte> RCKT_HATCH_L { get; set; }
        public Nullable<byte> RCKT_CARGO_H { get; set; }
        public Nullable<byte> RCKT_CARGO_M { get; set; }
        public Nullable<byte> RCKT_CARGO_L { get; set; }
        public Nullable<byte> CARGO_SCORE { get; set; }
        public Nullable<byte> CARGO_HATCH { get; set; }
        public Nullable<byte> CLIMB1 { get; set; }
        public Nullable<byte> CLIMB2 { get; set; }
        public Nullable<byte> CLIMB3 { get; set; }
        public Nullable<byte> CARGO_FLOOR { get; set; }
        public Nullable<byte> HATCH_PASS { get; set; }
        public string Comments { get; set; }
    }
}
